# -*- coding: utf-8 -*-
"""CanvasAutomationTaskProject-v1.3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_kLUcHb_T2-5vGA2UrmJEongBgX7FLWA
"""

# You can ignore this cell completely if you are not working in Colab.
#import os
#from google.colab import userdata

# Map your Colab Secrets to Environment Variables
#secret_names = [
#    "CANVAS_URL",
#    "CANVAS_KEY",
#    "GOOGLE_CLIENT_ID",
#    "GOOGLE_CLIENT_SECRET",
#    "GOOGLE_REFRESH_TOKEN",
#    "TELEGRAM_BOT_TOKEN",
#    "TELEGRAM_CHAT_ID"
#]

#for name in secret_names:
#    try:
#        val = userdata.get(name)
#        if val:
#            os.environ[name] = val
#            print(f"✅ Loaded {name}")
#        else:
#            print(f"⚠️ {name} is empty.")
#    except userdata.SecretNotFoundError:
#        print(f"❌ Secret not found: {name}")

"""The purpose of this script is the automation of homework and exam search for my courses enrolled in Tecsup."""

import os
from datetime import datetime, timezone
import zoneinfo
import google_tasks_manager as gtm
try:
    from telegram_sender import send_telegram_message
except ImportError:
    send_telegram_message = None

# Try to get secrets from Colab first; fall back to environment variables
try:
    !pip install canvasapi
    from canvasapi import Canvas
    from google.colab import userdata
    API_URL = userdata.get('CANVAS_URL')
    API_KEY = userdata.get('CANVAS_KEY')
except ImportError:
    # Not in Colab – use environment variables (GitHub Actions)
    API_URL = os.getenv("CANVAS_URL")
    API_KEY = os.getenv("CANVAS_KEY")

if not API_URL or not API_KEY:
    raise RuntimeError("Missing CANVAS_URL or CANVAS_KEY environment variables.")
canvas = Canvas(API_URL, API_KEY)
LOCAL_TZ = zoneinfo.ZoneInfo("America/Lima")   # GMT-5

def get_submitted_assignment_ids(canvas):
    """
    Return a set of Canvas assignment IDs for which the user has submitted work.
    We consider 'submitted' or 'graded' as done.
    """
    user = canvas.get_current_user()
    courses = user.get_courses(enrollment_state="active")
    submitted_ids = set()

    for course in courses:
        if not hasattr(course, 'name'):
            continue
        try:
            # Fetch submissions for this specific course for the current user
            submissions = course.get_submissions(student_ids=[user.id], workflow_state="submitted")
            for sub in submissions:
                if hasattr(sub, 'assignment_id') and sub.assignment_id:
                    submitted_ids.add(sub.assignment_id)
        except Exception as e:
            # Some courses may not allow this, skip them
            print(f"Could not fetch submissions for {course.name}: {e}")
            pass
    return submitted_ids

def get_tasks():
    print("Conecting a Canvas...\n")
    user = canvas.get_current_user()
    courses = user.get_courses(enrollment_state="active")
    now_local = datetime.now(LOCAL_TZ)
    start_of_today = now_local.replace(hour=0, minute=0, second=0, microsecond=0)
    pending_items = []

    for course in courses:
        if not hasattr(course, 'name'):
            continue
        print(f"Analyzing: {course.name}...")
        try:
            assignments = course.get_assignments()
            for task in assignments:
              if task.due_at:
                # Parse UTC timestamp and convert to local time
                due_utc = datetime.strptime(
                    task.due_at, "%Y-%m-%dT%H:%M:%SZ"
                ).replace(tzinfo=timezone.utc)
                due_local = due_utc.astimezone(LOCAL_TZ)
                # Filter: Only show tasks that are due as of today
                if due_local >= start_of_today:
                  pending_items.append({
                      "Course_name": course.name,
                      "Assignment_id": task.id,
                      "Type": "Task",
                      "Name": task.name,
                      "Due_local": due_local, # datetime object
                      "Link": task.html_url
                  })
        except Exception as e:
            # Sometimes there are no permissions or the course does not have the module active
            pass
    return pending_items


def filter_and_add_to_google_tasks(pending_items):
    """
    Filter pending_items: remove already submitted and already in Google Tasks.
    Then add the remaining new tasks to Google Tasks.
    Returns a tuple (newly_added, already_existing_or_submitted) for the report.
    """
    # 1. Get submitted assignment IDs
    try:
        submitted_ids = get_submitted_assignment_ids(canvas)
        print(f"Retrieved {len(submitted_ids)} submitted assignments.")
    except Exception as e:
        print(f"Warning: Could not fetch submissions: {e}")
        submitted_ids = set()

    # 2. Get existing Google Tasks (to avoid duplicates)
    try:
        existing_tasks = gtm.list_tasks()
        print(f"Retrieved {len(existing_tasks)} existing Google Tasks.")
    except Exception as e:
        print(f"Warning: Could not fetch Google Tasks: {e}")
        existing_tasks = []

    new_to_add = []
    already_done = []

    for item in pending_items:
        # Check submission
        if item["assignment_id"] in submitted_ids:
            already_done.append(item)
            continue

        # Check if already in Google Tasks by link
        if gtm.task_exists_by_url(item["link"], existing_tasks):
            already_done.append(item)
            continue

        new_to_add.append(item)

    # 3. Add new tasks to Google Tasks
    added_count = 0
    for item in new_to_add:
        try:
            due_rfc = gtm.format_due_rfc3339(item["due_local"])
            notes = f"Course: {item['Course_name']}\nLink: {item['link']}"
            gtm.add_task(
                title=item["name"],
                due_rfc3339=due_rfc,
                notes=notes
            )
            added_count += 1
            print(f"Added: {item['name']}")
        except Exception as e:
            print(f"Failed to add task '{item['name']}': {e}")

    return new_to_add, already_done, added_count

def build_report(new_tasks, old_tasks, added_count):
    report_lines = []
    report_lines.append("=" * 50)
    report_lines.append("📋 <b>REPORT OF PENDING ASSIGNMENTS AND EXAMS</b>")
    report_lines.append("=" * 50)
    if added_count > 0:
        report_lines.append(f"📚 Added {added_count} new tasks to Google Tasks:")
        for item in new_tasks:
            due_str = item["due_local"].strftime("%d/%m %H:%M")
            report_lines.append(f"• {item['course_name']} – {item['name']} (due {due_str})")
            report_lines.append(f"🔗  <a href='{item['link']}'>Open in Canvas</a>")
            report_lines.append("-" * 30)
    else:
        report_lines.append("✅ Up to date! No pending tasks.")
    if old_tasks:
        report_lines.append(f"\n📌 Already submitted or in Google Tasks: {len(old_tasks)}")
        # Optionally list a few
        for item in old_tasks[:5]:
            report_lines.append(f"  - {item['Course_name']}: {item['name']}")
    return "\n".join(report_lines)

if __name__ == "__main__":
    pending = get_tasks()
    print(f"Total pending assignments (due today or later): {len(pending)}")
    new_tasks, old_tasks, added = filter_and_add_to_google_tasks(pending)

    report_text = build_report(new_tasks, old_tasks, added)

    # Print to console (Actions log)
    print(report_text)
    if send_telegram_message:
      try:
        send_telegram_message(report_text)
      except Exception as e:
            print(f"Telegram send failed: {e}")
    else:
        print("telegram_sender module not found – cannot send Telegram message.")