# -*- coding: utf-8 -*-
"""get_refresh_token.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yyCToWstmJ54xSWFJEOBlLFZZqzECMk1
"""

!pip install google-auth-oauthlib google-api-python-client

import json
from google_auth_oauthlib.flow import InstalledAppFlow
import os

SCOPES = ['https://www.googleapis.com/auth/tasks']

def main():
    os.environ["OAUTHLIB_INSECURE_TRANSPORT"] = "1" # Set this environment variable to allow insecure HTTP for local testing

    with open('client_secret_XXXX.json', 'r') as f:
        client_config = json.load(f)
    REDIRECT_URI = 'http://localhost:8081'

    flow = InstalledAppFlow.from_client_config(client_config, SCOPES)
    flow.redirect_uri = REDIRECT_URI # <-- Manually set this value

    auth_url, _ = flow.authorization_url(
        access_type='offline',
        prompt='consent'
    )

    print("Step 1: Copy this URL and open it in a clean browser:")
    print(auth_url)
    redirect_url = input("\nStep 2: After authorizing, paste the ENTIRE URL from your browser address bar here: ")
    flow.fetch_token(authorization_response=redirect_url)
    creds = flow.credentials
    print("✅ Refresh token:", creds.refresh_token)
    print("✅ Token expiration:", creds.token_expiry)
    if creds.refresh_token:
      print(f"✅ Token successfully generated. Length: {len(creds.refresh_token)} characters.")
      print("Looks like a valid token.")
    else:
      print("❌ Error: No refresh token found!")
    print("Copy this token and store it safely (GitHub secret).")

if __name__ == "__main__":
    main()

from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build

# Paste your token here temporarily for testing
creds = Credentials(token=None, refresh_token='PASTE_YOUR_TOKEN_HERE',
                    token_uri="https://oauth2.googleapis.com/token",
                    client_id="YOUR_CLIENT_ID", client_secret="YOUR_CLIENT_SECRET")

service = build('tasks', 'v1', credentials=creds)
result = service.tasklists().list().execute()
print("Success! Your token is valid. Task lists found:", result)