# -*- coding: utf-8 -*-
"""google_tasks_manager.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QfvRkJRIY828nMR39ZpxAsD2833-Wr8L
"""

"""
google_tasks_manager.py
Provides functions to interact with Google Tasks via a stored refresh token.
"""
import os
import logging
from datetime import datetime, timezone
import zoneinfo
from google.auth.transport.requests import Request
from googleapiclient.discovery import build
from google.oauth2.credentials import Credentials
from google.auth.exceptions import RefreshError

# Setup logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)
LOCAL_TZ = zoneinfo.ZoneInfo("America/Lima")

def _get_credentials():
    """Build and refresh credentials from environment variables."""
    try:
      client_id = os.getenv("GOOGLE_CLIENT_ID")
      client_secret = os.getenv("GOOGLE_CLIENT_SECRET")
      refresh_token = os.getenv("GOOGLE_REFRESH_TOKEN")
    except:
      from google.colab import userdata
      client_id = userdata.get("GOOGLE_CLIENT_ID")
      client_secret = userdata.get("GOOGLE_CLIENT_SECRET")
      refresh_token = userdata.get("GOOGLE_REFRESH_TOKEN")

    if not all([client_id, client_secret, refresh_token]):
        raise ValueError("Missing Google OAuth credentials in environment variables.")

    creds = Credentials(
        None,
        refresh_token=refresh_token,
        token_uri="https://oauth2.googleapis.com/token",
        client_id=client_id,
        client_secret=client_secret,
    )
    # Force a refresh to obtain a valid access token
    try:
        creds.refresh(Request())
    except RefreshError as e:
        logger.error(f"Failed to refresh Google token: {e}")
        raise
    return creds

def get_service():
    """Return an authorized Google Tasks API service."""
    creds = _get_credentials()
    return build("tasks", "v1", credentials=creds)

def list_tasks(tasklist="@default", show_completed=False):
    """
    Retrieve all tasks from the specified task list.
    Returns a list of task dicts (id, title, due, notes).
    """
    service = get_service()
    tasks = []
    page_token = None

    while True:
        result = service.tasks().list(
            tasklist=tasklist,
            showCompleted=show_completed,
            fields="nextPageToken,tasks(id,title,due,notes)",
            maxResults=100,
            pageToken=page_token
        ).execute()
        tasks.extend(result.get("tasks", []))
        page_token = result.get("nextPageToken")
        if not page_token:
            break
    return tasks

def add_task(title, due_rfc3339, notes, tasklist="@default"):
    """
    Add a new task to the specified task list.
    due_rfc3339: string like '2026-07-25T23:59:00-05:00'
    """
    service = get_service()
    task_body = {
        "title": title,
        "notes": notes,
        "due": due_rfc3339,
    }
    try:
        result = service.tasks().insert(tasklist=tasklist, body=task_body).execute()
        logger.info(f"Task added: {result['title']}")
        return result
    except Exception as e:
        logger.error(f"Failed to add task '{title}': {e}")
        raise

def task_exists_by_url(assignment_url, existing_tasks):
    """
    Check if a task with notes containing the given Canvas assignment URL already exists.
    """
    for task in existing_tasks:
        notes = task.get("notes", "")
        if assignment_url in notes:
            return True
    return False

def format_due_rfc3339(dt_local: datetime) -> str:
    """
    Convert a local datetime (aware) to RFC 3339 string with UTC offset.
    We want to preserve the local time as the due time; Google Tasks will interpret it
    in the given offset. So we format with -05:00.
    """
    dt_local = dt_local.astimezone(LOCAL_TZ)
    return dt_local.strftime("%Y-%m-%dT%H:%M:%S%z")

# Local test for _get_credentials() function
try:
  from google.colab import userdata
  client_id = userdata.get("GOOGLE_CLIENT_ID")
  client_secret = userdata.get("GOOGLE_CLIENT_SECRET")
  refresh_token = userdata.get("GOOGLE_REFRESH_TOKEN")
  os.environ["GOOGLE_CLIENT_ID"] = client_id
  os.environ["GOOGLE_CLIENT_SECRET"] = client_secret
  os.environ["GOOGLE_REFRESH_TOKEN"] = refresh_token
  creds = _get_credentials()
  if creds:
    print("Credentials obtained successfully.")
    #print(creds.token)
  else:
    print("Failed to obtain credentials.")
except ModuleNotFoundError:
  print("Skipping local credentials test (Non-Colab / CI environment).")
except Exception as e:
  print(f"An error occurred during local credential testing: {e}")